### ISSUE TITLE
Qt 5.12.1 Windows MinGW 7.3.0 64bit Need to add #include <QAction> in vsrtl_netlist.cpp

### ISSUE THREAD

**Issue by mars4zhu** [mortbopet/VSRTL#19]
Qt 5.12.1 Windows MinGW 7.3.0 64bit Need to add `#include <QAction>` in vsrtl_netlist.cpp

or, the compiler will complain as:

...\VSRTL\graphics\vsrtl_netlist.cpp:17:68: error: invalid use of incomplete type 'class
QAction'
     QAction* expandAct = new QAction(expandIcon, "Expand All", this);

**Comment by mortbopet** [comment]
Thank you for reporting the issue - i'll add MinGW to the list of compilers which should be used in CI.

**Comment by mortbopet** [comment]
Please let me know if this fixed the issue.

**Comment by mars4zhu** [comment]
> Please let me know if this fixed the issue.

It fixes.
