### ISSUE TITLE
Add windows CI

### ISSUE THREAD

**Issue by mortbopet** [mortbopet/VSRTL#23]
Currently, travis CI compiles and runs on linux and OSX.
Windows-based continuous integration should be enabled, possibly through appveyor or Travis' experimental windows environment.

**Comment by mars4zhu** [comment]
Is this issue come from my problem fo compiling VSRTL on windows using QT 5.12.1 with MinGW compiler ?

THank you for your attention to my problem , I am interested in your VRSTL and PIPE project.

**Comment by mortbopet** [comment]
Yes - Ideally, windows CI should have jobs for both MSVC, MinGW and a job executing unit tests.
