### ISSUE TITLE
Missing include <cstdint>?

### ISSUE THREAD

**Issue by hcmh** [mortbopet/VSRTL#60]
Good morning,

I tried to compile Ripes from git, as outlined in that README, and hit the following issue:

compilation failed with
```
Ripes/external/VSRTL/interface/vsrtl_vcdfile.h:32:49: error: ‘uint64_t’ has not been declared
   32 |     void writeVarChange(const std::string& ref, uint64_t value);
```

simply adding `#include <cstdint>`  after https://github.com/mortbopet/VSRTL/blob/a7f17baf2f5cee4a9946d987a74348ab75375d25/interface/vsrtl_vcdfile.h#L7

fixed the issue for me.

By the way, I am using Arch Linux and gcc 13.2.1

**Comment by mortbopet** [comment]
Looks like it! Added in https://github.com/mortbopet/VSRTL/commit/c64b83c03da19594a9e9b3fd4456edb29364cc86
